### ISSUE TITLE
Add process labels metadata

### ISSUE THREAD

**Issue by stuartcarnie** [stuartcarnie/gopm#7]
## What

Add key / value labels to `program` descriptions in the yaml configuration file. For example:

```yaml
  - name: procA
    command: bin/procA
    labels:
      group: core
  - name: procB
    command: bin/procB
  - name: procC
    command: bin/procC
    tags:
      group: core
```

These would allow extensions to commands using tags:

```sh
$ gopmctl start -l group=core
```
